### PR TITLE
More keywords available in formulas: bilaplacian, trilaplacian, x_gradient, gaussian, x_pos.

### LINKED ISSUE #87: Provide bilaplacian, x_gradient, etc. when needed
This would allow more rules to be formula rules rather than full kernels.

Scan the formula for reserved keywords (laplacian_a, bilaplacian_b, x_gradient_a, etc.) and provide the ones that are used.

### PR DESCRIPTION
**Pull request by timhutton**
- Formulas now support more stencils: `bilaplacian_a`, `trilaplacian_a`, `gaussian_a`, `sobel_ne_a`, `x_gradient_a`, `y_gradient_a`, `z_gradient_a`, `gradient_mag_squared_a` (and similarly for the other chemicals). Several patterns have been converted from kernel rules to formula rules as a result: 
  - Experiments\CornusAmmonis\splats.vti
  - Experiments\TihaVonGhyczy\sobel_waves.vti
  - Pennybacker2013\parameter_map.vti
  - Pennybacker2013\phyllotaxis_fibonacci.vti
  - Pennybacker2013\phyllotaxis_hexagons.vti
  - Pennybacker2013\spots.vti
  - Pennybacker2013\stripes.vti
  - advection.vti
  - bilaplacian_interpolation.vti
- Formulas now support `x_pos`, `y_pos` and `z_pos`, giving the cell location in each direction, in the range [0,1]. This allows a neater and more accurate way of implementing parameter maps. Previously rules would do e.g. `hpos = index_x / X` which would give the 4x1x1 block position, not the cell position.
- Parameter `dx` is now reserved for controlling the grid spacing of the Gaussian, Laplacian, bi-Laplacian, tri-Laplacian and gradient stencils. Formula rules no longer need to write e.g. `laplacian_a / (delta_x * delta_x)` and can just write `laplacian_a` since the value of `dx` is used in the stencil computation.
- stencils.hpp/.cpp implements a generic engine for constructing N-dimensional stencils and converting them to OpenCL code.
- `neighborhood_range` and `neighborhood_weight` parameters in the XML format for the `<rule>` node are no longer supported. Not much of this was implemented and it doesn't do what we wanted. The intention was to allow the same formulas to work on meshes as well as images with different stencils but it wasn't the right approach - it doesn't allow us to use e.g. a laplacian and bilaplacian in the same formula.
- Moved View Full Kernel... and Show OpenCL Diagnostics... to the View menu.

This closes #87

### CODE REVIEW

**Comment by danwills** [comment]
Wow Tim you've been busy! Bloody awesome work mate!

I am super keen to check all of this out, and I'll also try to make sure that the Houdini importer can load all the updated formulas correctly. 

I was about ready to commit a new version in a branch, but will fold any changes from this in as well.

**Comment by timhutton** [comment]
@danwills Will these changes cause problems with the Houdini importer? I hadn't thought about that.

**Comment by danwills** [comment]
It's all good @timhutton I expect most things that used to work in the plugin probably still will but I might be able to extend (or 'fix') support for the new things formula mode can now do. That should vastly extend the number of things that can be imported as well, so definitely a worthwhile effort I reckon! :)

**Comment by danwills** [comment]
If you're happy with the changes I wouldn't want to hold up this pull request due to rdyHoudini (especially considering it's currently in a broken state for Houdini 18.5 anyway!).

I would love to preview this branch though, I'll checkout the trunk and apply this pull request later on, and hopefully give this branch a bit of testing for you : )

**Pull request merged**
