### PR TITLE
Houdini plugin branch

### PR DESCRIPTION
**Pull request by danwills**
Hi ReadyGang,
I reckon I'm finished integrating the Ready Houdini plugin build into the main cmake! : ) It can be enabled by switching on a cmake boolean called PLUGIN_BUILD (and sourcing the houdini environment). The plugin can be installed to the default place in the ~/houdiniX.Y/dso folder in the user's home directory using 'make install'.

I added a src/plugins/houdini/README.txt with some instructions on how to build it. I made an example hipfile and also included an otl (houdini digital asset) file that contains the definition of a helper geometry node in Houdini that makes it easier to prepare geometry to store the simulation data.

The PLUGIN_BUILD boolean enables the flag -fPIC to generate relocatable code in libreadybase. It also defines "__EXTERNAL_OPENCL__" which causes methods to be added to readybase that allow it to be initialised with the openCL context provided by the host application.

I have been struggling with build/environment issues but I think I have them all sorted now, so I'd love to be able to merge my changes with gh-pages :). I've only tested one platform (gentoo linux x86_64), so if y'all could take this for a test-run, that would be absolutely awesome! I'd be happy to talk you through the houdini GUI side of things if you're interested in that too. It's not very polished in that regard so far.

If you don't have houdini installed, but would like to install it, you can get 'Apprentice' (the free version, which is fairly unencumbered apart from watermarked renders and no render-farming) here:
http://www.sidefx.com/index.php?option=com_download&task=apprentice&Itemid=208

Thanks heaps,
Dan

### CODE REVIEW

**Comment by timhutton** [comment]
Hi Dan,

Thanks for doing this. I've been having a look at it, on a Windows 10 box:
1. For compiling Ready without the Houdini plugin, the changes to the CMakeLists for linking vtk libs (vtkRenderingOpenGL2/vtkRenderingOpenGL for 6.3+ and
   vtkRenderingFreeTypeOpenGL/vtkRenderingOpenGL for 6.0-6.2) both cause problems for me, when building with either VTK 6.0 or 6.3. What versions of VTK were you using to test these?
2. I installed Houdini Apprentice but I haven't yet managed to build the plugin because CMake asks for things like H_LIB_HoudiniUI and I don't know what it means. Any help would be appreciated.

I'll try the build in Ubuntu, see whether this casts any light on these two issues.

We'll also need some build instructions. Perhaps in a separate BUILD-Houdini.txt file.

Regards,

Tim

**Comment by timhutton** [comment]
Blocking issues:
1. On Windows and on Ubuntu, the changes to the CMakeLists for linking vtk libs (vtkRenderingOpenGL2/vtkRenderingOpenGL for 6.3+ and vtkRenderingFreeTypeOpenGL/vtkRenderingOpenGL for 6.0-6.2) both cause problems, when building with either VTK 6.0 or 6.3. If these changes are needed for compilation in gentoo then suggest either detecting the distro in the CMakeLists.txt or making a note in BUILD.txt.

Strong suggestions but not blocking:
1. Need build instructions for the Houdini plugin. Ideally usage instructions too.

---

Hope that's fair. Sorry about the delay. I really appreciate the pull request and I hope we can get it merged. 

Tim

**Comment by danwills** [comment]
Thanks heaps for taking a look Tim! Yep that's totally fair.

I find it a bit odd that there should be distro-specific issues like this with VTK, and I suspect that there might be something else going on (like maybe I managed to build VTK with custom use-flags or something..). For now I'll go ahead and figure out how to detect distro in the cmake and use it to switch the extra flags in (for gentoo) and out (elsewhere), so that it builds on other systems again.

It looks like this command might be helpful for that purpose:
  /usr/bin/lsb_release

I'd love to hear any advice or preference for how to detect distro name, if you have any :).

I'll also flesh out the plugin build instructions and add an explanatory usage example when I get a chance.

Thanks heaps for your feedback! we'll get it sorted soon I hope,
Dan

**Comment by danwills** [comment]
I think we can close this pull request now.. not delete the branch in case someone else wants to refer to it later.. though maybe it would be better to neuter it (conflict/build-issues-wise) and merge that into gh-pages, to make it more discoverable for hypothetical future plugin developers?
Edit: hit close a bit too soon there!

**Pull request closed without merging**
