### PR TITLE
Added a rule-info argument to rdy

### PR DESCRIPTION
**Pull request by danwills**
Added a rule-info argument which provides the rule's type, name, neighborhood_type, neighborhood_range and neighborhood_weight, which allows differentiation between formula-mode and full-kernel.

It's a tiny change but fairly important at the Houdini end. I don't think it will affect the build at all.

Am settling on some methods in Houdini and will soon provide initial versions of the new HDAs that use the new rdy command.

### CODE REVIEW

**Comment by timhutton** [comment]
Tabs -> spaces, please.

**Comment by danwills** [comment]
Apologies Tim I still needed to reconfigure my editor (I think I've set it correctly now). 

I tried to commit+push a tabs->spaces version but something seems to have not worked as I don't see it in github yet.

**Review by timhutton — APPROVED** [review]
Still some trailing whitespace but it's fine. Thanks Dan.

**Comment by danwills** [comment]
Thanks Tim! All merged :)
I've got SublimeText now and am loving it, that will hopefully help with my whitespace sillyness.

**Comment by timhutton** [comment]
@danwills After merging, you can delete the branch, to keep things tidy. Looks like there are two here - ```origin/rdy-rule-info-arg``` and ```rdy-rule-info-arg``` (which might explain the commit confusion above).

**Comment by danwills** [comment]
Yeah, thanks Tim I've now deleted the branches.. seems like one was the one I created on the github website and the other was from trying to commit with the wrong git commandline args :/

Still getting used to git I guess, apologies for the mess! and thanks for your patient guidance.

**Pull request merged**
